export const data = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i1",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i2",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i3",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i4",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i5",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i6",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i7",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i8",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m5gr84i0",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m1gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "m2gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
]